### ISSUE TITLE
SSL_CERT_FILE seems to be leaner and potentially provides more coverage than patching

### ISSUE THREAD

**Issue by mrahs** [google/oss-rebuild#145]
The variable is used by OpenSSL and any program that links against it. I'm wondering if setting `--docker_truststore_env_vars=SSL_CERT_FILE` was deemed insufficient compared to manually patching trust stores in https://github.com/google/oss-rebuild/blob/de8aaef11881c6d114354d0f33e6b19c16d8c16f/pkg/proxy/docker/linux.go#L26-L55

**Comment by msuozzo** [comment]
> The variable is used by OpenSSL and any program that links against it.

What about those that don't 😄 

But beyond that, during the internal deployment experiment, there were numerous cases where env vars were insufficient, ignored, or lost (think `sudo`). Both redirecting and directly modifying the container truststore offer incomplete assurance that the truststore cert is trusted. By combining the techniques, we increase our odds of not breaking the proxied build.

**Comment by mrahs** [comment]
Yep, I forgot about `sudo`. That's fair.
